import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../core/utils/snackbar_utils.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/theme/common_methods.dart';
import 'package:tailoring_flutter/l10n/app_localizations.dart';
import '../domain/entities/template.dart';
import 'bloc/template_bloc.dart';
import 'bloc/template_event.dart';
import 'bloc/template_state.dart';
import '../../../core/widgets/app_back_button.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Preset measurement field names
// ─────────────────────────────────────────────────────────────────────────────

const _presetFields = [
  'BUST',
  'WAIST',
  'HIP',
  'SHOULDER',
  'SLEEVE',
  'LENGTH',
  'CHEST',
  'FLARE',
  'THIGH',
  'KNEE',
  'ANKLE',
  'NECK',
  'SLIT',
  'ARM HOLE',
  'BACK DEPTH',
  'FRONT DEPTH',
];

// ─────────────────────────────────────────────────────────────────────────────
// Widget
// ─────────────────────────────────────────────────────────────────────────────

class AddTemplateFieldsScreen extends StatefulWidget {
  final String templateName;
  final String category;
  final int iconCodePoint;
  final String? iconFontFamily;
  final double basePrice;

  const AddTemplateFieldsScreen({
    super.key,
    required this.templateName,
    required this.category,
    required this.iconCodePoint,
    this.iconFontFamily,
    required this.basePrice,
  });

  @override
  State<AddTemplateFieldsScreen> createState() =>
      _AddTemplateFieldsScreenState();
}

class _AddTemplateFieldsScreenState extends State<AddTemplateFieldsScreen> {
  final List<String> _fields = [];
  final _customFieldCtrl = TextEditingController();

  @override
  void dispose() {
    _customFieldCtrl.dispose();
    super.dispose();
  }

  void _addPresetField(String field) {
    if (_fields.contains(field)) return;
    setState(() => _fields.add(field));
  }

  void _addCustomField() {
    final text = _customFieldCtrl.text.trim().toUpperCase();
    if (text.isEmpty || _fields.contains(text)) return;
    setState(() {
      _fields.add(text);
      _customFieldCtrl.clear();
    });
  }

  void _removeField(int index) => setState(() => _fields.removeAt(index));

  void _onReorder(int oldIndex, int newIndex) {
    setState(() {
      if (newIndex > oldIndex) newIndex--;
      final item = _fields.removeAt(oldIndex);
      _fields.insert(newIndex, item);
    });
  }

  void _onSave(AppColorScheme c) {
    if (widget.templateName.isEmpty) {
      showAppSnackBar(
        context,
        message: AppLocalizations.of(context).missingTemplateInfo,
        isError: true,
      );
      return;
    }
    /* if (_fields.isEmpty) {
      showAppSnackBar(context, message: 'Add at least one measurement field.', isError: true);
      return;
    } */

    final template = Template(
      id: '', // Will be generated by backend/repository
      name: widget.templateName,
      category: widget.category,
      iconCodePoint: widget.iconCodePoint,
      iconFontFamily: widget.iconFontFamily,
      fields: List.from(_fields),
      basePrice: widget.basePrice,
    );

    context.read<TemplateBloc>().add(AddTemplate(template));
  }

  @override
  Widget build(BuildContext context) {
    final c = getThemeBaseColors(context);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    final topGradient = isDark
        ? c.colorPrimaryDark.withValues(alpha: 0.8)
        : c.colorAccent.withValues(alpha: 0.95);
    final midGradient = isDark
        ? c.colorPrimaryDark.withValues(alpha: 0.4)
        : c.colorAccent.withValues(alpha: 0.2);

    return BlocListener<TemplateBloc, TemplateState>(
      listener: (context, state) {
        if (state is TemplateAddSuccess) {
          context.pop(true);
          context.pop(true);
          showAppSnackBar(
            context,
            message: AppLocalizations.of(context).templateSaved,
          );
        } else if (state is TemplateError) {
          showAppSnackBar(context, message: state.message, isError: true);
        }
      },
      child: Scaffold(
        backgroundColor: c.background,
        body: Stack(
          children: [
            Positioned(
              top: 0,
              left: 0,
              right: 0,
              height: MediaQuery.of(context).size.height * 0.40,
              child: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      topGradient,
                      midGradient,
                      c.background.withValues(alpha: 0.0),
                    ],
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                  ),
                ),
              ),
            ),
            SafeArea(
              child: Column(
                children: [
                  _buildHeader(c, isDark),
                  Expanded(child: _buildBody(c, isDark)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Header ────────────────────────────────────────────────────────────────
  Widget _buildHeader(AppColorScheme c, bool isDark) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(20, 16, 20, 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                decoration: BoxDecoration(
                  color: isDark
                      ? Colors.white.withValues(alpha: 0.1)
                      : Colors.black.withValues(alpha: 0.05),
                  shape: BoxShape.circle,
                ),
                child: AppBackButton(onTap: () => context.pop()),
              ),
              Text(
                AppLocalizations.of(context).createTemplate,
                style: GoogleFonts.poppins(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: c.textDark,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: 12,
                  vertical: 6,
                ),
                decoration: BoxDecoration(
                  color: c.colorPrimary.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  AppLocalizations.of(
                    context,
                  ).fieldsCountSuffix(_fields.length),
                  style: GoogleFonts.poppins(
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                    color: c.colorPrimary,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                AppLocalizations.of(context).measurementFields,
                style: GoogleFonts.poppins(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                  color: c.textDark,
                ),
              ),
              Text(
                AppLocalizations.of(context).step2of2,
                style: GoogleFonts.poppins(
                  fontSize: 12,
                  color: c.textDark.withValues(alpha: 0.7),
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          Row(
            children: List.generate(
              2,
              (i) => Expanded(
                child: Container(
                  margin: EdgeInsets.only(right: i < 1 ? 6 : 0),
                  height: 5,
                  decoration: BoxDecoration(
                    color: c.colorPrimary,
                    borderRadius: BorderRadius.circular(3),
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  // ── Body ──────────────────────────────────────────────────────────────────
  Widget _buildBody(AppColorScheme c, bool isDark) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Quick-add preset chips
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                AppLocalizations.of(context).quickAdd,
                style: GoogleFonts.poppins(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: c.textDark,
                ),
              ),
              const SizedBox(height: 10),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: _presetFields.map((field) {
                  final added = _fields.contains(field);
                  return GestureDetector(
                    onTap: () => _addPresetField(field),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 180),
                      padding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 7,
                      ),
                      decoration: BoxDecoration(
                        color: added
                            ? c.colorPrimary
                            : c.colorPrimary.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(
                          color: added
                              ? c.colorPrimary
                              : c.colorPrimary.withValues(alpha: 0.2),
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          if (added)
                            const Padding(
                              padding: EdgeInsets.only(right: 4),
                              child: Icon(
                                Icons.check,
                                color: Colors.white,
                                size: 12,
                              ),
                            ),
                          Text(
                            getLocalizedMeasurementField(
                              field,
                              AppLocalizations.of(context),
                            ),
                            style: GoogleFonts.poppins(
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                              color: added ? Colors.white : c.colorPrimary,
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                }).toList(),
              ),
              const SizedBox(height: 16),
              Text(
                AppLocalizations.of(context).fieldsList,
                style: GoogleFonts.poppins(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: c.textDark,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                _fields.isEmpty
                    ? AppLocalizations.of(context).noFieldsAdded
                    : AppLocalizations.of(context).dragToRemove,
                style: GoogleFonts.poppins(fontSize: 12, color: c.gray),
              ),
            ],
          ),
        ),
        const SizedBox(height: 8),

        // Reorderable list
        Expanded(
          child: _fields.isEmpty
              ? Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.straighten_outlined,
                        size: 52,
                        color: c.gray.withValues(alpha: 0.5),
                      ),
                      const SizedBox(height: 12),
                      Text(
                        AppLocalizations.of(context).noFieldsAdded,
                        style: GoogleFonts.poppins(fontSize: 14, color: c.gray),
                      ),
                    ],
                  ),
                )
              : ReorderableListView.builder(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  itemCount: _fields.length,
                  onReorder: _onReorder,
                  proxyDecorator: (child, index, animation) =>
                      Material(color: Colors.transparent, child: child),
                  itemBuilder: (context, index) =>
                      _buildFieldTile(c, isDark, _fields[index], index),
                ),
        ),

        // Custom field input
        _buildCustomFieldInput(c, isDark),

        // Save button
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 24),
          child: SizedBox(
            width: double.infinity,
            child: BlocBuilder<TemplateBloc, TemplateState>(
              builder: (context, state) {
                final isLoading = state is TemplateLoading;
                return ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: c.colorPrimary,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                    elevation: 0,
                  ),
                  onPressed: isLoading ? null : () => _onSave(c),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      isLoading
                          ? const SizedBox(
                              width: 20,
                              height: 20,
                              child: CircularProgressIndicator(
                                color: Colors.white,
                                strokeWidth: 2,
                              ),
                            )
                          : const Icon(
                              Icons.check_circle_outline,
                              color: Colors.white,
                              size: 20,
                            ),
                      const SizedBox(width: 8),
                      Text(
                        isLoading
                            ? AppLocalizations.of(context).saving
                            : AppLocalizations.of(context).saveTemplate,
                        style: GoogleFonts.poppins(
                          fontSize: 15,
                          fontWeight: FontWeight.w600,
                          color: Colors.white,
                        ),
                      ),
                    ],
                  ),
                );
              },
            ),
          ),
        ),
      ],
    );
  }

  // ── Field tile ────────────────────────────────────────────────────────────
  Widget _buildFieldTile(
    AppColorScheme c,
    bool isDark,
    String field,
    int index,
  ) {
    return Container(
      key: ValueKey('$field-$index'),
      margin: const EdgeInsets.only(bottom: 10),
      decoration: BoxDecoration(
        color: isDark ? c.cardDark : Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: c.divider.withValues(alpha: 0.4)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 8,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: ListTile(
        contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
        leading: Icon(Icons.drag_handle, color: c.gray.withValues(alpha: 0.6)),
        title: Container(
          padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
          decoration: BoxDecoration(
            color: c.colorPrimary.withValues(alpha: 0.08),
            borderRadius: BorderRadius.circular(6),
          ),
          child: Text(
            getLocalizedMeasurementField(field, AppLocalizations.of(context)),
            style: GoogleFonts.poppins(
              fontSize: 12,
              fontWeight: FontWeight.bold,
              color: c.colorPrimary,
            ),
          ),
        ),
        trailing: GestureDetector(
          onTap: () => _removeField(index),
          child: Container(
            padding: const EdgeInsets.all(6),
            decoration: BoxDecoration(
              color: Colors.red.withValues(alpha: 0.08),
              shape: BoxShape.circle,
            ),
            child: Icon(Icons.close, size: 16, color: Colors.red.shade400),
          ),
        ),
      ),
    );
  }

  // ── Custom field input ────────────────────────────────────────────────────
  Widget _buildCustomFieldInput(AppColorScheme c, bool isDark) {
    return Container(
      margin: const EdgeInsets.fromLTRB(20, 8, 20, 16),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      decoration: BoxDecoration(
        color: isDark ? c.cardDark : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: c.divider.withValues(alpha: 0.5)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 10,
            offset: const Offset(0, 3),
          ),
        ],
      ),
      child: Row(
        children: [
          Icon(Icons.add_circle_outline, color: c.colorPrimary, size: 20),
          const SizedBox(width: 10),
          Expanded(
            child: TextField(
              controller: _customFieldCtrl,
              textCapitalization: TextCapitalization.characters,
              style: GoogleFonts.poppins(fontSize: 13, color: c.textDark),
              decoration: InputDecoration(
                hintText: AppLocalizations.of(context).addCustomFieldHint,
                hintStyle: GoogleFonts.poppins(fontSize: 13, color: c.gray),
                border: InputBorder.none,
                isDense: true,
                contentPadding: const EdgeInsets.symmetric(vertical: 12),
              ),
              onSubmitted: (_) => _addCustomField(),
            ),
          ),
          GestureDetector(
            onTap: _addCustomField,
            child: Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: c.colorPrimary,
                shape: BoxShape.circle,
              ),
              child: const Icon(Icons.add, color: Colors.white, size: 16),
            ),
          ),
        ],
      ),
    );
  }
}
