import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:geolocator/geolocator.dart';
import 'package:geocoding/geocoding.dart';
import 'package:google_fonts/google_fonts.dart';

import 'package:flutter/material.dart';

import 'package:flutter_bloc/flutter_bloc.dart';
import '../../auth/bloc/auth_bloc.dart';
import '../../auth/bloc/auth_event.dart';
import '../../auth/bloc/auth_state.dart';
import '../../auth/data/models/profile_model.dart';
import '../../auth/data/models/shop_model.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/common_methods.dart';
import '../../../main.dart';
import '../../../core/utils/snackbar_utils.dart';
import '../../../routes/app_router.dart';
import 'package:go_router/go_router.dart';
import 'package:tailoring_flutter/l10n/app_localizations.dart';

class ShopSetupScreen extends ConsumerStatefulWidget {
  const ShopSetupScreen({super.key});

  @override
  ConsumerState<ShopSetupScreen> createState() => _ShopSetupScreenState();
}

class _ShopSetupScreenState extends ConsumerState<ShopSetupScreen>
    with SingleTickerProviderStateMixin {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  // Step 1
  final _shopNameCtrl = TextEditingController();
  final _ownerNameCtrl = TextEditingController();
  final _addressCtrl = TextEditingController();
  bool _isLoadingLocation = false;
  late AnimationController _shimmerCtrl;

  // Step 2
  double _capacity = 12;
  final List<int> _workingDays = [0, 1, 2, 3, 4, 5]; // Indexes from 0 to 6
  TimeOfDay _openTime = const TimeOfDay(hour: 10, minute: 0);
  TimeOfDay _closeTime = const TimeOfDay(hour: 20, minute: 0);

  // Step 3
  String _language = 'English';
  final _gstinCtrl = TextEditingController();

  @override
  void initState() {
    super.initState();
    _shimmerCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1500),
    )..repeat();
  }

  @override
  void dispose() {
    _shimmerCtrl.dispose();
    _pageController.dispose();
    _shopNameCtrl.dispose();
    _ownerNameCtrl.dispose();
    _addressCtrl.dispose();
    _gstinCtrl.dispose();
    super.dispose();
  }

  void _nextPage() {
    if (_currentPage < 2) {
      _pageController.animateToPage(
        _currentPage + 1,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    } else {
      _saveDataAndNavigate();
    }
  }

  void _saveDataAndNavigate() {
    final authState = context.read<AuthBloc>().state;
    if (authState is AuthAuthenticated) {
      final user = authState.user;
      
      // Save Profile
      final profile = ProfileModel(
        id: user.id,
        fullName: _ownerNameCtrl.text,
        email: user.email,
      );
      context.read<AuthBloc>().add(ProfileUpdated(profile));

      // Save Shop
      final shop = ShopModel(
        id: '', // Will be generated by Supabase if upsert handles it or we can pass empty
        ownerId: user.id,
        name: _shopNameCtrl.text,
        ownerName: _ownerNameCtrl.text,
        address: _addressCtrl.text,
        capacity: _capacity.toInt(),
        workingDays: _workingDays,
        openTime: _formatTimeOfDay(_openTime),
        closeTime: _formatTimeOfDay(_closeTime),
        gstin: _gstinCtrl.text,
      );
      context.read<AuthBloc>().add(ShopUpdated(shop));
    }
    context.push(AppRoutes.allSet);
  }

  String _formatTimeOfDay(TimeOfDay t) {
    final h = t.hourOfPeriod == 0 ? 12 : t.hourOfPeriod;
    final m = t.minute.toString().padLeft(2, '0');
    final period = t.period == DayPeriod.am ? 'AM' : 'PM';
    return '$h:$m $period';
  }

  void _prevPage() {
    if (_currentPage > 0) {
      _pageController.animateToPage(
        _currentPage - 1,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    } else {
      context.pop();
    }
  }

  Future<void> _getCurrentLocation() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if (mounted) {
        showAppSnackBar(context, message: 'Location services are disabled.', isError: true);
      }
      return;
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        if (mounted) {
          showAppSnackBar(context, message: 'Location permissions are denied.', isError: true);
        }
        return;
      }
    }

    if (permission == LocationPermission.deniedForever) {
      if (mounted) {
        showAppSnackBar(context, message: 'Location permissions are permanently denied.', isError: true);
      }
      return;
    }

    setState(() {
      _isLoadingLocation = true;
    });

    try {
      final position = await Geolocator.getCurrentPosition(
        locationSettings: const LocationSettings(
          accuracy: LocationAccuracy.medium,
        ),
      );
      List<Placemark> placemarks = await placemarkFromCoordinates(
        position.latitude,
        position.longitude,
      );
      if (placemarks.isNotEmpty) {
        final place = placemarks.first;
        final address =
            '${place.name}, ${place.street}, ${place.subLocality}, ${place.locality}, ${place.postalCode}';
        setState(() {
          _addressCtrl.text = address;
        });
      }
    } catch (e) {
      if (mounted) {
        showAppSnackBar(context, message: 'Could not fetch address.', isError: true);
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoadingLocation = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    // Force light theme colors as requested
    final c = getThemeBaseColors(context);

    return Scaffold(
      backgroundColor: c.background,
      body: Column(
        children: [
          _buildHeader(c, l10n),
          Expanded(
            child: PageView(
              controller: _pageController,
              physics: const NeverScrollableScrollPhysics(),
              onPageChanged: (idx) => setState(() => _currentPage = idx),
              children: [
                _buildStep1(c, l10n),
                _buildStep2(c, l10n),
                _buildStep3(c, l10n)
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeader(AppColorScheme c, AppLocalizations l10n) {
    String eyebrow = '';
    String title = '';
    String subtitle = '';
    if (_currentPage == 0) {
      eyebrow = l10n.setupStep(1, 3).toUpperCase();
      title = l10n.shopDetailsTitle;
      subtitle = l10n.shopDetailsSubtitle;
    } else if (_currentPage == 1) {
      eyebrow = l10n.setupStep(2, 3).toUpperCase();
      title = l10n.businessSettingsTitle;
      subtitle = l10n.businessSettingsSubtitle;
    } else {
      eyebrow = l10n.setupStep(3, 3).toUpperCase();
      title = l10n.finalSetupTitle;
      subtitle = l10n.finalSetupSubtitle;
    }

    final statusBarH = MediaQuery.of(context).padding.top;

    return Stack(
      children: [
        // ── Same lavender fade gradient as home / orders / templates ──
        Container(
          width: double.infinity,
          height: statusBarH + 220,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                c.colorAccent.withValues(alpha: 0.95),
                c.colorAccent.withValues(alpha: 0.2),
                c.background.withValues(alpha: 0.0)
              ],
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
            ),
          ),
        ),

        // ── Header content ──
        Container(
          width: double.infinity,
          padding: EdgeInsets.fromLTRB(24, statusBarH + 16, 24, 28),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Back button + step pill
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  // White circle back button — same as create-order screens
                  GestureDetector(
                    onTap: _prevPage,
                    child: Container(
                      width: 40,
                      height: 40,
                      decoration: BoxDecoration(
                        color: Colors.white,
                        shape: BoxShape.circle,
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withValues(alpha: 0.07),
                            blurRadius: 10,
                            offset: const Offset(0, 3),
                          ),
                        ],
                      ),
                      child: Icon(
                        Icons.arrow_back_ios_new,
                        color: c.textDark,
                        size: 16,
                      ),
                    ),
                  ),

                  // Step pill
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 14,
                      vertical: 7,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(20),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.05),
                          blurRadius: 8,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                    child: Text(
                      'Step ${_currentPage + 1} of 3',
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: c.colorPrimary,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),

              // Eyebrow
              Text(
                eyebrow,
                style: GoogleFonts.poppins(
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.2,
                  color: c.textDark.withValues(alpha: 0.55),
                ),
              ),
              const SizedBox(height: 4),

              // Page title
              Text(
                title,
                style: GoogleFonts.poppins(
                  fontSize: 26,
                  fontWeight: FontWeight.bold,
                  color: c.textDark,
                  height: 1.15,
                ),
              ),
              const SizedBox(height: 4),

              // Subtitle
              Text(
                subtitle,
                style: GoogleFonts.poppins(
                  fontSize: 13,
                  color: c.textDark.withValues(alpha: 0.6),
                ),
              ),
              const SizedBox(height: 20),

              // 3-segment progress bar
              Row(
                children: List.generate(3, (index) {
                  return Expanded(
                    child: Container(
                      margin: EdgeInsets.only(right: index < 2 ? 8 : 0),
                      height: 5,
                      decoration: BoxDecoration(
                        color: index <= _currentPage
                            ? c.colorPrimary
                            : c.colorPrimary.withValues(alpha: 0.18),
                        borderRadius: BorderRadius.circular(3),
                      ),
                    ),
                  );
                }),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildStep1(AppColorScheme c, AppLocalizations l10n) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _label(c, l10n.shopNameLabel),
          _textField(
            c,
            _shopNameCtrl,
            l10n.shopNameHint,
            Icons.store_outlined,
          ),
          const SizedBox(height: 24),
          _label(c, l10n.ownerNameLabel),
          _textField(
            c,
            _ownerNameCtrl,
            l10n.ownerNameHint,
            Icons.person_outline,
          ),
          const SizedBox(height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _label(c, l10n.shopAddressLabel),
              TextButton.icon(
                onPressed: _getCurrentLocation,
                icon: Icon(Icons.my_location, size: 16, color: c.colorPrimary),
                label: Text(
                  l10n.useCurrentLocation,
                  style: GoogleFonts.poppins(
                    fontSize: 12,
                    color: c.colorPrimary,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                style: TextButton.styleFrom(
                  padding: EdgeInsets.zero,
                  minimumSize: Size.zero,
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          _isLoadingLocation
              ? _buildLocationSkeleton(c)
              : TextField(
                  controller: _addressCtrl,
                  maxLines: 3,
                  style: GoogleFonts.poppins(fontSize: 14, color: c.textDark),
                  decoration: InputDecoration(
                    hintText: l10n.shopAddressHint,
                    hintStyle: GoogleFonts.poppins(fontSize: 14, color: c.gray),
                    filled: true,
                    fillColor: c.white,
                    contentPadding: const EdgeInsets.all(16),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(16),
                      borderSide: BorderSide(color: c.divider),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(16),
                      borderSide: BorderSide(color: c.divider),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(16),
                      borderSide: BorderSide(color: c.colorPrimary, width: 1.5),
                    ),
                  ),
                ),
          const SizedBox(height: 8),
          Text(
            l10n.addressTip,
            style: GoogleFonts.poppins(fontSize: 11, color: c.gray),
          ),
          const SizedBox(height: 32),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: c.colorPrimary.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(16),
            ),
            child: Row(
              children: [
                Icon(Icons.info, color: c.colorPrimary, size: 20),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    l10n.shopInfoTip,
                    style: GoogleFonts.poppins(fontSize: 12, color: c.textDark),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 32),
          _buildNextButton(c, l10n),
        ],
      ),
    );
  }

  Widget _buildStep2(AppColorScheme c, AppLocalizations l10n) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _label(c, l10n.dailyCapacityLabel),
          Text(
            l10n.dailyCapacitySub,
            style: GoogleFonts.poppins(fontSize: 13, color: c.gray),
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            decoration: BoxDecoration(
              color: c.colorPrimary.withValues(alpha: 0.05),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Row(
              children: [
                Expanded(
                  child: SliderTheme(
                    data: SliderTheme.of(context).copyWith(
                      activeTrackColor: c.colorPrimary,
                      inactiveTrackColor: c.colorPrimary.withValues(alpha: 0.1),
                      thumbColor: c.colorPrimary,
                      overlayColor: c.colorPrimary.withValues(alpha: 0.2),
                    ),
                    child: Slider(
                      value: _capacity,
                      min: 1,
                      max: 50,
                      divisions: 49,
                      onChanged: (v) => setState(() => _capacity = v),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: c.colorPrimary,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${_capacity.toInt()} ${l10n.items}',
                    style: GoogleFonts.poppins(
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 32),
          _label(c, l10n.workingDaysLabel),
          Text(
            l10n.workingDaysSub,
            style: GoogleFonts.poppins(fontSize: 13, color: c.gray),
          ),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: List.generate(7, (index) {
              final localizedDays = [
                l10n.dayMon,
                l10n.dayTue,
                l10n.dayWed,
                l10n.dayThu,
                l10n.dayFri,
                l10n.daySat,
                l10n.daySun,
              ];
              final day = localizedDays[index];
              final isSelected = _workingDays.contains(index);
              return GestureDetector(
                onTap: () {
                  setState(() {
                    if (isSelected) {
                      _workingDays.remove(index);
                    } else {
                      _workingDays.add(index);
                    }
                  });
                },
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    color: isSelected ? c.colorPrimary : c.grayLight,
                    shape: BoxShape.circle,
                    boxShadow: isSelected
                        ? [
                            BoxShadow(
                              color: c.colorPrimary.withValues(alpha: 0.4),
                              blurRadius: 8,
                              offset: const Offset(0, 4),
                            ),
                          ]
                        : [],
                  ),
                  alignment: Alignment.center,
                  child: Text(
                    day,
                    style: GoogleFonts.poppins(
                      color: isSelected ? c.white : c.gray,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              );
            }),
          ),
          const SizedBox(height: 32),
          _label(c, l10n.shopTimingsLabel),
          Text(
            l10n.shopTimingsSub,
            style: GoogleFonts.poppins(fontSize: 13, color: c.gray),
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(child: _timePicker(c, l10n.opening, _openTime, true)),
              const SizedBox(width: 16),
              Expanded(child: _timePicker(c, l10n.closing, _closeTime, false)),
            ],
          ),
          const SizedBox(height: 40),
          _buildNextButton(c, l10n),
        ],
      ),
    );
  }

  Widget _buildStep3(AppColorScheme c, AppLocalizations l10n) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _label(c, l10n.appLanguageLabel),
          const SizedBox(height: 12),
          Wrap(
            spacing: 12,
            runSpacing: 12,
            children: [
              _langChip(c, 'English', 'en'),
              _langChip(c, 'हिंदी', 'hi'),
              _langChip(c, 'ગુજરાતી', 'gu'),
              _langChip(c, 'मराठी', 'mr'),
              _langChip(c, 'தமிழ்', 'ta'),
            ],
          ),
          const SizedBox(height: 32),
          _label(c, '${l10n.businessDetailsLabel} (${l10n.optional})'),
          _textField(
            c,
            _gstinCtrl,
            l10n.gstinHint,
            Icons.receipt_long_outlined,
          ),
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4),
            child: Text(
              l10n.gstinTip,
              style: GoogleFonts.poppins(fontSize: 12, color: c.gray),
            ),
          ),
          const SizedBox(height: 40),
          _buildNextButton(c, l10n),
          const SizedBox(height: 24),
          Center(
            child: Text(
              l10n.termsConditionTip,
              textAlign: TextAlign.center,
              style: GoogleFonts.poppins(
                fontSize: 11,
                color: c.gray,
                letterSpacing: 0.5,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildNextButton(AppColorScheme c, AppLocalizations l10n) {
    return GestureDetector(
      onTap: _nextPage,
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 18),
        decoration: BoxDecoration(
          color: c.colorPrimary,
          borderRadius: BorderRadius.circular(20),
          boxShadow: [
            BoxShadow(
              color: c.colorPrimary.withValues(alpha: 0.3),
              blurRadius: 15,
              offset: const Offset(0, 8),
            ),
          ],
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              _currentPage == 2 ? l10n.completeSetup : l10n.nextStep,
              style: GoogleFonts.poppins(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(width: 8),
            const Icon(Icons.arrow_forward, color: Colors.white, size: 20),
          ],
        ),
      ),
    );
  }

  Widget _timePicker(
    AppColorScheme c,
    String label,
    TimeOfDay time,
    bool isOpening,
  ) {
    return GestureDetector(
      onTap: () async {
        final t = await showTimePicker(
          context: context,
          initialTime: time,
        );
        if (t != null) setState(() => isOpening ? _openTime = t : _closeTime = t);
      },
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        decoration: BoxDecoration(
          border: Border.all(color: c.divider),
          borderRadius: BorderRadius.circular(16),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              label,
              style: GoogleFonts.poppins(
                fontSize: 10,
                fontWeight: FontWeight.w600,
                color: c.gray,
              ),
            ),
            const SizedBox(height: 4),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  time.format(context),
                  style: GoogleFonts.poppins(
                    fontSize: 15,
                    fontWeight: FontWeight.w600,
                    color: c.textDark,
                  ),
                ),
                Icon(Icons.access_time, color: c.gray, size: 16),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _label(AppColorScheme c, String text, {bool padding = true}) {
    return Padding(
      padding: EdgeInsets.only(bottom: padding ? 8 : 0),
      child: Text(
        text,
        style: GoogleFonts.poppins(
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: c.textDark,
        ),
      ),
    );
  }

  Widget _textField(
    AppColorScheme c,
    TextEditingController ctrl,
    String hint,
    IconData? icon,
  ) {
    return TextField(
      controller: ctrl,
      style: GoogleFonts.poppins(fontSize: 14, color: c.textDark),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: GoogleFonts.poppins(fontSize: 14, color: c.gray),
        prefixIcon: icon != null ? Icon(icon, color: c.gray, size: 20) : null,
        filled: true,
        fillColor: c.white,
        contentPadding: const EdgeInsets.symmetric(
          vertical: 16,
          horizontal: 16,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: c.divider),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: c.divider),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(16),
          borderSide: BorderSide(color: c.colorPrimary, width: 1.5),
        ),
      ),
    );
  }

  Widget _buildLocationSkeleton(AppColorScheme c) {
    return AnimatedBuilder(
      animation: _shimmerCtrl,
      builder: (context, child) {
        return Container(
          height: 90,
          width: double.infinity,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
              stops: [0.0, _shimmerCtrl.value, 1.0],
              colors: [
                c.grayLight.withValues(alpha: 0.5),
                c.grayLight,
                c.grayLight.withValues(alpha: 0.5),
              ],
            ),
          ),
        );
      },
    );
  }
  Widget _langChip(AppColorScheme c, String name, String code) {
    final isSelected = _language == name;
    return GestureDetector(
      onTap: () {
        setState(() => _language = name);
        appLocaleProvider.setLocale(Locale(code));
      },
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        decoration: BoxDecoration(
          color: isSelected ? c.colorPrimary : c.white,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? c.colorPrimary : c.divider,
            width: 1,
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: c.colorPrimary.withValues(alpha: 0.3),
                    blurRadius: 8,
                    offset: const Offset(0, 4),
                  )
                ]
              : [],
        ),
        child: Text(
          name,
          style: GoogleFonts.poppins(
            fontSize: 13,
            fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
            color: isSelected ? Colors.white : c.textDark,
          ),
        ),
      ),
    );
  }
}
