// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlRQ98JRNp50wTLDKf6y9z9E91ZXtj82Q',
    appId: '1:146499208329:web:532bbdec0c392ba63ab258',
    messagingSenderId: '146499208329',
    projectId: 'tailoring-app-b6f10',
    authDomain: 'tailoring-app-b6f10.firebaseapp.com',
    storageBucket: 'tailoring-app-b6f10.firebasestorage.app',
    measurementId: 'G-11BBTWB661',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LDYZC7WI0iORe73kKDfslKWhZFWRy30',
    appId: '1:146499208329:android:1bf5cbeababe0ced3ab258',
    messagingSenderId: '146499208329',
    projectId: 'tailoring-app-b6f10',
    storageBucket: 'tailoring-app-b6f10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyKa1Qb41BfF0K8Q08sHkfNKi4F2jqkE',
    appId: '1:146499208329:ios:133bf9401c79413a3ab258',
    messagingSenderId: '146499208329',
    projectId: 'tailoring-app-b6f10',
    storageBucket: 'tailoring-app-b6f10.firebasestorage.app',
    iosClientId: '146499208329-ovetnmshns440ae3hkicfsk87gch0omt.apps.googleusercontent.com',
    iosBundleId: 'com.meet.tailoringFlutter',
  );
}
